# Generated by Django 2.2.7 on 2021-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='product_thumbnails')),
                ('cover', models.ImageField(upload_to='product_covers')),
                ('sub_cover1', models.ImageField(blank=True, null=True, upload_to='cub_covers')),
                ('sub_cover2', models.ImageField(blank=True, null=True, upload_to='cub_covers')),
                ('sub_cover3', models.ImageField(blank=True, null=True, upload_to='cub_covers')),
                ('sub_cover4', models.ImageField(blank=True, null=True, upload_to='cub_covers')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('Beds', 'Beds'), ('Tables', 'Tables'), ('Sofas', 'Sofas')], max_length=40)),
                ('quality_one', models.CharField(blank=True, default='', max_length=100)),
                ('quality_two', models.CharField(blank=True, default='', max_length=100)),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='please-input-in-this-format', max_length=100)),
            ],
        ),
    ]
